name: eopf-zarr
channels:
- conda-forge
dependencies:
   - python=3.11.7
   - xarray
   - matplotlib
   - mystmd
   - pip
   - pip:
     - git+https://gitlab.eopf.copernicus.eu/cpm/eopf-cpm.git
     - jupyter_server
